version: '3.8'

services:
  traefik:
    image: traefik:v3.0.0-rc2
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=mayer.julien22@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "letsencrypt:/letsencrypt"
    networks:
      - monitoring_network
    restart: unless-stopped

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    network_mode: "host"
    volumes:
      - open-webui:/app/backend/data
    environment:
      - OLLAMA_API_BASE_URL=http://127.0.0.1:11434/api
    restart: always
    
  prometheus:
    image: prom/prometheus:v2.51.0
    volumes:
      - /etc/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    restart: unless-stopped
    networks:
      - monitoring_network

  alertmanager:
    image: prom/alertmanager:v0.27.0-rc.0
    volumes:
      - /etc/alertmanager:/etc/alertmanager
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
    restart: unless-stopped
    networks:
      - monitoring_network

  grafana:
    image: grafana/grafana:10.4.1
    depends_on:
      - prometheus
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`grafana.h4ckm1n.org`)"
      - "traefik.http.routers.grafana.entrypoints=websecure"
      - "traefik.http.routers.grafana.tls.certresolver=myresolver"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - monitoring_network
    restart: unless-stopped

  nodeexporter:
    image: prom/node-exporter:v1.7.0
    volumes:
      - "/:/host:ro,rslave"
    command:
      - '--path.rootfs=/host'
    restart: unless-stopped
    networks:
      - monitoring_network

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.49.1
    volumes: 
      - "/:/rootfs"
      - "/var/run:/var/run"
      - "/sys:/sys"
      - "/var/lib/docker/:/var/lib/docker"
      - "/dev/disk/:/dev/disk"
    privileged: true
    devices: 
      - "/dev/kmsg"
    restart: unless-stopped
    networks:
      - monitoring_network

  loki:
    image: grafana/loki:2.9.6
    command:
      - -config.file=/etc/loki/local-config.yaml
    volumes:
      - loki_data:/loki
    restart: unless-stopped
    networks:
      - monitoring_network

  promtail:
    image: grafana/promtail:2.9.6
    volumes:
      - "/var/log:/var/log"
      - "/var/lib/docker/containers:/var/lib/docker/containers:ro"
      - "/etc/promtail:/etc/promtail"
    command:
      - -config.file=/etc/promtail/config.yml
    restart: unless-stopped
    networks:
      - monitoring_network

  watchtower:
    image: containrrr/watchtower:1.7.1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    command:
      - --interval 30
    restart: unless-stopped
    networks:
      - monitoring_network

volumes:
  open-webui:
  prometheus_data:
  grafana_data:
  loki_data:
  letsencrypt:

networks:
  monitoring_network:
    driver: bridge
