global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "nodeexporter"
    static_configs:
      - targets: ["nodeexporter:9100"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: "nvidia-cuda-exporter"
    static_configs:
      - targets: ["nvidia-cuda-exporter:8888"]
      
  - job_name: "blackbox-https"
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - https://google.com
          - https://amazon.com
          - https://openai.com
          - https://facebook.com
          - https://instagram.com
          - https://youtube.com
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115
      - source_labels: [__param_module]
        target_label: module
